apiVersion: v1
kind: Pod
metadata:
  name: etcd-cluster
spec:
  hostNetwork: true
  containers:
  - image: mosquitood/docker-etcd:3.1.6
    name: etcd-container
    command:
    - /bin/etcd
    - --name=etcd-node3
    - --initial-advertise-peer-urls=https://192.168.18.226:2380
    - --listen-peer-urls=https://192.168.18.226:2380
    - --listen-client-urls=https://192.168.18.226:2379,http://127.0.0.1:2379   
    - --advertise-client-urls=https://192.168.18.226:2379   
    - --data-dir=/var/etcd/data
    - --discovery=https://discovery.etcd.io/7ea3025baf93f7915c33787be8f83766
    - --cert-file=/etc/etcd/ssl/etcd.pem
    - --key-file=/etc/etcd/ssl/etcd-key.pem
    - --trusted-ca-file=/etc/ca/ssl/ca.pem 
    - --peer-cert-file=/etc/etcd/ssl/etcd.pem
    - --peer-key-file=/etc/etcd/ssl/etcd-key.pem
    - --peer-trusted-ca-file=/etc/ca/ssl/ca.pem
    ports:
    - name: serverport
      containerPort: 2380
      hostPort: 2380
    - name: clientport
      containerPort: 2379 
      hostPort: 2379 
    volumeMounts:
    - mountPath: /var/etcd/data
      name: varetcd
    - mountPath: /etc/etcd/ssl
      name: etcdssl
      readOnly: true
    - mountPath: /etc/ca/ssl
      name: usrcassl
      readOnly: true
  volumes:
  - hostPath:
      path: /var/etcd/data
    name: varetcd
  - hostPath:
      path: /etc/etcd/ssl
    name: etcdssl
  - hostPath:
      path: /etc/kubernetes/ssl
    name: usrcassl
