apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: mosquitood/kube-scheduler:v1.8.4
    command:
    - /usr/local/bin/kube-scheduler 
    - --address=127.0.0.1 
    - --master=https://192.168.18.250:7443 
    - --leader-elect=true 
    - --v=2
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /var/log/kube-scheduler.log
      name: logfile
  volumes:
  - hostPath:
      path: /var/log/kube-scheduler.log
    name: logfile
